### ISSUE TITLE
Exporting slides in Windows 11

### ISSUE THREAD

**Issue by Pinzauti** [bojanczyk/slajdomat#8]
As there is not a bundle for Windows I tried to compile the app myself with npm. `npm install` works fine, and so does `npm run make` or `npm start`, without any error. 
Selecting the presentation folder works too, however when trying to export the slide from the Figma plugin to the app the following error appears:
`Error receiving slide Error: ENOENT: no such file or directory, copyfile "C:\Users\franc\Desktop\slajdomat-master/resources/index.html" -> "C:\Users\franc\Desktop/Untitled/index.html"`.

Not sure if of any help but [here is the compiled version](https://we.tl/t-qlHRhItCU1).

Any suggestion?

P.S: seeing the error was possible modifying `server.ts` as in https://github.com/bojanczyk/slajdomat/pull/6.

**Comment by bojanczyk** [comment]
I think that this has been resolved. Now the index.html is stored in some more official place.
